export const companies = {
    easy: [
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.invalid.com",
            "market_cap": 7889326592,
            "name": "RBC Bearings Incorporated",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "RBC",
            "website": "https://www.rbcbearings.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.rh.com",
            "market_cap": 7889900000,
            "name": "RH",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "RH",
            "website": "https://www.rh.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.amg.com",
            "market_cap": 7889000000,
            "name": "Affiliated Managers Group, Inc.",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "AMG",
            "website": "https://www.amg.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.usbank.com",
            "market_cap": 69656461312,
            "name": "U.S. Bancorp",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "USB",
            "website": "https://www.usbank.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.ussteel.com",
            "market_cap": 9167995904,
            "name": "United States Steel Corporation",
            "revenue_growth": null,
            "sector": "Basic Materials",
            "ticker": "X",
            "website": "https://www.ussteel.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.poolcorp.com",
            "market_cap": 15484796928,
            "name": "Pool Corporation",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "POOL",
            "website": "https://www.poolcorp.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.williams.com",
            "market_cap": 47481827328,
            "name": "Williams Companies, Inc. (The)",
            "revenue_growth": null,
            "sector": "Energy",
            "ticker": "WMB",
            "website": "https://www.williams.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.extraspace.com",
            "market_cap": 32161982464,
            "name": "Extra Space Storage Inc",
            "revenue_growth": null,
            "sector": "Real Estate",
            "ticker": "EXR",
            "website": "https://www.extraspace.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.dollargeneral.com",
            "market_cap": 34281857024,
            "name": "Dollar General Corporation",
            "revenue_growth": null,
            "sector": "Consumer Defensive",
            "ticker": "DG",
            "website": "https://www.dollargeneral.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.pinterest.com",
            "market_cap": 23540338688,
            "name": "Pinterest, Inc.",
            "revenue_growth": null,
            "sector": "Communication Services",
            "ticker": "PINS",
            "website": "https://www.pinterest.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.usfoods.com",
            "market_cap": 13217415168,
            "name": "US Foods Holding Corp.",
            "revenue_growth": null,
            "sector": "Consumer Defensive",
            "ticker": "USFD",
            "website": "https://www.usfoods.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.bbwinc.com",
            "market_cap": 11249347584,
            "name": "Bath & Body Works, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "BBWI",
            "website": "https://www.bbwinc.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.flowersfoods.com",
            "market_cap": 5000966656,
            "name": "Flowers Foods, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Defensive",
            "ticker": "FLO",
            "website": "https://www.flowersfoods.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.dollartree.com",
            "market_cap": 29024436224,
            "name": "Dollar Tree, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Defensive",
            "ticker": "DLTR",
            "website": "https://www.dollartree.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.popular.com",
            "market_cap": 6364854784,
            "name": "Popular, Inc.",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "BPOP",
            "website": "https://www.popular.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.americanexpress.com",
            "market_cap": 163945676800,
            "name": "American Express Company",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "AXP",
            "website": "https://www.americanexpress.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.genpt.com",
            "market_cap": 21600804864,
            "name": "Genuine Parts Company",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "GPC",
            "website": "https://www.genpt.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.cableone.biz",
            "market_cap": 2377614080,
            "name": "Cable One, Inc.",
            "revenue_growth": null,
            "sector": "Communication Services",
            "ticker": "CABO",
            "website": "https://www.cableone.biz"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.nike.com",
            "market_cap": 142390984704,
            "name": "Nike, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "NKE",
            "website": "https://www.nike.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.creditacceptance.com",
            "market_cap": 6785719296,
            "name": "Credit Acceptance Corporation",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "CACC",
            "website": "https://www.creditacceptance.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.corporate.carrier.com",
            "market_cap": 52322988032,
            "name": "Carrier Global Corporation",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "CARR",
            "website": "https://www.corporate.carrier.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.plugpower.com",
            "market_cap": 2353837056,
            "name": "Plug Power, Inc.",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "PLUG",
            "website": "https://www.plugpower.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.americanairlines.in/intl/in/index.jsp",
            "market_cap": 10050520064,
            "name": "American Airlines Group, Inc.",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "AAL",
            "website": "https://www.americanairlines.in/intl/in/index.jsp"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.airbnb.com",
            "market_cap": 105222217728,
            "name": "Airbnb, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "ABNB",
            "website": "https://www.airbnb.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.essential.co",
            "market_cap": 10133767168,
            "name": "Essential Utilities, Inc.",
            "revenue_growth": null,
            "sector": "Utilities",
            "ticker": "WTRG",
            "website": "https://www.essential.co"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.block.xyz",
            "market_cap": 52075315200,
            "name": "Block, Inc.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "SQ",
            "website": "https://www.block.xyz"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.gendigital.com",
            "market_cap": 14266783744,
            "name": "Gen Digital Inc.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "GEN",
            "website": "https://www.gendigital.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.westerndigital.com",
            "market_cap": 22236686336,
            "name": "Western Digital Corporation",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "WDC",
            "website": "https://www.westerndigital.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.premierinc.com",
            "market_cap": 2647977728,
            "name": "Premier, Inc.",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "PINC",
            "website": "https://www.premierinc.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "easy",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.publicstorage.com",
            "market_cap": 51105669120,
            "name": "Public Storage",
            "revenue_growth": null,
            "sector": "Real Estate",
            "ticker": "PSA",
            "website": "https://www.publicstorage.com"
        }
    ],
    medium: [
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.hp.com",
            "market_cap": 29569695744,
            "name": "HP Inc.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "HPQ",
            "website": "https://www.hp.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.unitedrentals.com",
            "market_cap": 48437178368,
            "name": "United Rentals, Inc.",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "URI",
            "website": "https://www.unitedrentals.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.unitedhealthgroup.com",
            "market_cap": 456080752640,
            "name": "UnitedHealth Group Incorporated",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "UNH",
            "website": "https://www.unitedhealthgroup.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.cbrands.com",
            "market_cap": 49683165184,
            "name": "Constellation Brands, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Defensive",
            "ticker": "STZ",
            "website": "https://www.cbrands.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.up.com",
            "market_cap": 150040903680,
            "name": "Union Pacific Corporation",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "UNP",
            "website": "https://www.up.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.fnf.com",
            "market_cap": 14507291648,
            "name": "FNF Group of Fidelity National ",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "FNF",
            "website": "https://www.fnf.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.pennentertainment.com",
            "market_cap": 2775622912,
            "name": "PENN Entertainment, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "PENN",
            "website": "https://www.pennentertainment.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.whitemountains.com",
            "market_cap": 4584759808,
            "name": "White Mountains Insurance Group",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "WTM",
            "website": "https://www.whitemountains.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.revvity.com",
            "market_cap": 12970125312,
            "name": "Revvity, Inc.",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "RVTY",
            "website": "https://www.revvity.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.crowncastle.com",
            "market_cap": 45985251328,
            "name": "Crown Castle Inc.",
            "revenue_growth": null,
            "sector": "Real Estate",
            "ticker": "CCI",
            "website": "https://www.crowncastle.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.autodesk.com",
            "market_cap": 55707750400,
            "name": "Autodesk, Inc.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "ADSK",
            "website": "https://www.autodesk.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.deere.com",
            "market_cap": 114332770304,
            "name": "Deere & Company",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "DE",
            "website": "https://www.deere.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://schneider.com",
            "market_cap": 3984300032,
            "name": "Schneider National, Inc.",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "SNDR",
            "website": "https://schneider.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.qualcomm.com",
            "market_cap": 188938797056,
            "name": "QUALCOMM Incorporated",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "QCOM",
            "website": "https://www.qualcomm.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.crowncork.com",
            "market_cap": 9574132736,
            "name": "Crown Holdings, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "CCK",
            "website": "https://www.crowncork.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://shop.hasbro.com/en-in",
            "market_cap": 7844467712,
            "name": "Hasbro, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "HAS",
            "website": "https://shop.hasbro.com/en-in"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.gartner.com",
            "market_cap": 37164961792,
            "name": "Gartner, Inc.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "IT",
            "website": "https://www.gartner.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.kellanova.com",
            "market_cap": 19579373568,
            "name": "Kellanova",
            "revenue_growth": null,
            "sector": "Consumer Defensive",
            "ticker": "K",
            "website": "https://www.kellanova.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.corporate.charter.com",
            "market_cap": 41962905600,
            "name": "Charter Communications, Inc.",
            "revenue_growth": null,
            "sector": "Communication Services",
            "ticker": "CHTR",
            "website": "https://www.corporate.charter.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.illumina.com",
            "market_cap": 21820149760,
            "name": "Illumina, Inc.",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "ILMN",
            "website": "https://www.illumina.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.paramount.com",
            "market_cap": 8089216000,
            "name": "Paramount Global",
            "revenue_growth": null,
            "sector": "Communication Services",
            "ticker": "PARAA",
            "website": "https://www.paramount.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.dovercorporation.com",
            "market_cap": 24341653504,
            "name": "Dover Corporation",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "DOV",
            "website": "https://www.dovercorporation.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.citigroup.com",
            "market_cap": 121122308096,
            "name": "Citigroup, Inc.",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "C",
            "website": "https://www.citigroup.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.mrcy.com",
            "market_cap": 1751297024,
            "name": "Mercury Systems Inc",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "MRCY",
            "website": "https://www.mrcy.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.fisglobal.com",
            "market_cap": 42762248192,
            "name": "Fidelity National Information S",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "FIS",
            "website": "https://www.fisglobal.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.rossstores.com",
            "market_cap": 49409097728,
            "name": "Ross Stores, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "ROST",
            "website": "https://www.rossstores.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.pxd.com",
            "market_cap": 61326041088,
            "name": "Pioneer Natural Resources Compa",
            "revenue_growth": null,
            "sector": "Energy",
            "ticker": "PXD",
            "website": "https://www.pxd.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.choicehotels.com",
            "market_cap": 6261918720,
            "name": "Choice Hotels International, In",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "CHH",
            "website": "https://www.choicehotels.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.goldmansachs.com",
            "market_cap": 135551688704,
            "name": "Goldman Sachs Group, Inc. (The)",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "GS",
            "website": "https://www.goldmansachs.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "medium",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.spectrumbrands.com",
            "market_cap": 2694475264,
            "name": "Spectrum Brands Holdings, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Defensive",
            "ticker": "SPB",
            "website": "https://www.spectrumbrands.com"
        }
    ],
    hard: [
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.sbasite.com",
            "market_cap": 23427219456,
            "name": "SBA Communications Corporation",
            "revenue_growth": null,
            "sector": "Real Estate",
            "ticker": "SBAC",
            "website": "https://www.sbasite.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.unum.com",
            "market_cap": 10276855808,
            "name": "Unum Group",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "UNM",
            "website": "https://www.unum.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.10xgenomics.com",
            "market_cap": 4472337408,
            "name": "10x Genomics, Inc.",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "TXG",
            "website": "https://www.10xgenomics.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.53.com",
            "market_cap": 25434896384,
            "name": "Fifth Third Bancorp",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "FITB",
            "website": "https://www.53.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.dynatrace.com",
            "market_cap": 13746193408,
            "name": "Dynatrace, Inc.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "DT",
            "website": "https://www.dynatrace.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.tpg.com",
            "market_cap": 16301152256,
            "name": "TPG Inc.",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "TPG",
            "website": "https://www.tpg.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.nexteraenergy.com",
            "market_cap": 131170795520,
            "name": "NextEra Energy, Inc.",
            "revenue_growth": null,
            "sector": "Utilities",
            "ticker": "NEE",
            "website": "https://www.nexteraenergy.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://investor.clearwayenergy.com",
            "market_cap": 4542486528,
            "name": "Clearway Energy, Inc.",
            "revenue_growth": null,
            "sector": "Utilities",
            "ticker": "CWEN",
            "website": "https://investor.clearwayenergy.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.eogresources.com",
            "market_cap": 74147454976,
            "name": "EOG Resources, Inc.",
            "revenue_growth": null,
            "sector": "Energy",
            "ticker": "EOG",
            "website": "https://www.eogresources.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.marvell.com",
            "market_cap": 61382078464,
            "name": "Marvell Technology, Inc.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "MRVL",
            "website": "https://www.marvell.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.oshkoshcorp.com",
            "market_cap": 8177908224,
            "name": "Oshkosh Corporation (Holding Co",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "OSK",
            "website": "https://www.oshkoshcorp.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://elementsolutionsinc.com",
            "market_cap": 6044984832,
            "name": "Element Solutions Inc.",
            "revenue_growth": null,
            "sector": "Basic Materials",
            "ticker": "ESI",
            "website": "https://elementsolutionsinc.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.vontier.com",
            "market_cap": 6980903936,
            "name": "Vontier Corporation",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "VNT",
            "website": "https://www.vontier.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.sarepta.com",
            "market_cap": 12150520832,
            "name": "Sarepta Therapeutics, Inc.",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "SRPT",
            "website": "https://www.sarepta.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.vailresorts.com",
            "market_cap": 8461100032,
            "name": "Vail Resorts, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "MTN",
            "website": "https://www.vailresorts.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.globant.com",
            "market_cap": 8699123712,
            "name": "Globant S.A.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "GLOB",
            "website": "https://www.globant.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://shockwavemedical.com",
            "market_cap": 12177520640,
            "name": "ShockWave Medical, Inc.",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "SWAV",
            "website": "https://shockwavemedical.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.adm.com",
            "market_cap": 32023615488,
            "name": "Archer-Daniels-Midland Company",
            "revenue_growth": null,
            "sector": "Consumer Defensive",
            "ticker": "ADM",
            "website": "https://www.adm.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.topbuild.com",
            "market_cap": 14021781504,
            "name": "TopBuild Corp.",
            "revenue_growth": null,
            "sector": "Industrials",
            "ticker": "BLD",
            "website": "https://www.topbuild.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.fortrea.com",
            "market_cap": 3588515840,
            "name": "Fortrea Holdings Inc.",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "FTRE",
            "website": "https://www.fortrea.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.natera.com",
            "market_cap": 11044526080,
            "name": "Natera, Inc.",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "NTRA",
            "website": "https://www.natera.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.maravai.com",
            "market_cap": 2179638016,
            "name": "Maravai LifeSciences Holdings, ",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "MRVI",
            "website": "https://www.maravai.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.brighthousefinancial.com",
            "market_cap": 3240943616,
            "name": "Brighthouse Financial, Inc.",
            "revenue_growth": null,
            "sector": "Financial Services",
            "ticker": "BHF",
            "website": "https://www.brighthousefinancial.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.lambweston.com",
            "market_cap": 15379948544,
            "name": "Lamb Weston Holdings, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Defensive",
            "ticker": "LW",
            "website": "https://www.lambweston.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.hubspot.com",
            "market_cap": 31750615040,
            "name": "HubSpot, Inc.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "HUBS",
            "website": "https://www.hubspot.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.albemarle.com",
            "market_cap": 15482743808,
            "name": "Albemarle Corporation",
            "revenue_growth": null,
            "sector": "Basic Materials",
            "ticker": "ALB",
            "website": "https://www.albemarle.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.iqvia.com",
            "market_cap": 46029520896,
            "name": "IQVIA Holdings, Inc.",
            "revenue_growth": null,
            "sector": "Healthcare",
            "ticker": "IQV",
            "website": "https://www.iqvia.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.ansys.com",
            "market_cap": 30209099776,
            "name": "ANSYS, Inc.",
            "revenue_growth": null,
            "sector": "Technology",
            "ticker": "ANSS",
            "website": "https://www.ansys.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.onepeloton.com",
            "market_cap": 1572050688,
            "name": "Peloton Interactive, Inc.",
            "revenue_growth": null,
            "sector": "Consumer Cyclical",
            "ticker": "PTON",
            "website": "https://www.onepeloton.com"
        },
        {
            "currency": "USD",
            "date": "Sun, 31 Mar 2024 00:00:00 GMT",
            "difficulty": "hard",
            "earnings_growth": null,
            "full_time_employees": null,
            "img_url": "https://logo.clearbit.com/https://www.slb.com",
            "market_cap": 78508204032,
            "name": "Schlumberger N.V.",
            "revenue_growth": null,
            "sector": "Energy",
            "ticker": "SLB",
            "website": "https://www.slb.com"
        }
    ]
}